# -*- coding: utf-8 -*-
"""Mini Migration of Billing Data

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/14pY3sCQ5XVQzJWWmlP1jbiWy1chU9A9C
"""

import pandas as pd

df=pd.read_csv("invoices.csv")

print(df)

df=df.drop_duplicates()
df["amount"] = (df["amount"] * 100).round().astype(int)

df["amount"].dtype

print(df)

import os
import sqlite3

# Remove corrupted db if exists
if os.path.exists("migration.db"):
    os.remove("migration.db")

# Create fresh db
conn = sqlite3.connect("migration.db")

# Load into db
df.to_sql("invoices", conn, if_exists="replace", index=False)

print("Database created successfully!")

cursor = conn.cursor()

# Row count validation
cursor.execute("SELECT COUNT(*) FROM invoices")
db_count = cursor.fetchone()[0]

csv_count = len(df)

print("\nReconciliation Check:")
print("CSV Row Count:", csv_count)
print("DB Row Count:", db_count)

# Revenue validation
cursor.execute("SELECT SUM(amount) FROM invoices")
db_total = cursor.fetchone()[0]

csv_total = df["amount"].sum()

print("CSV Revenue Total:", csv_total)
print("DB Revenue Total:", db_total)

conn.close()

if csv_count == db_count and csv_total == db_total:
    print("\nMigration Successful")
else:
    print("\nMigration Failed")